services:
  - type: web
    name: n8n
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: n8n
    branch: main
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_CONNECTION_URL
        fromDatabase:
          name: n8n-db
          property: connectionString
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://your-service-name.onrender.com
